name: recipe
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.9.23
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - aiofile==3.9.0
      - aiofiles==25.1.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - argcomplete==3.6.3
      - argparse==1.4.0
      - astunparse==1.6.3
      - autorom==0.6.1
      - bokeh==3.4.3
      - boto3==1.40.74
      - botocore==1.40.74
      - bracex==2.6
      - cachetools==6.2.2
      - caio==0.9.24
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - chex==0.1.90
      - click==8.1.8
      - cloudpickle==3.1.1
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==0.29.37
      - d4rl==1.1
      - decorator==5.2.1
      - deepdiff==8.6.1
      - diffusers==0.24.0
      - dill==0.4.0
      - distrax==0.1.5
      - dm-control==1.0.34
      - dm-env==1.6
      - dm-env-rpc==1.1.6
      - dm-tree==0.1.8
      - einops==0.8.1
      - enum34==1.1.10
      - etils==1.5.2
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - expandvars==1.1.2
      - farama-notifications==0.0.4
      - fasteners==0.20
      - filelock==3.19.1
      - flashbax==0.1.3
      - flatbuffers==25.9.23
      - flax==0.8.5
      - fonttools==4.59.2
      - fpf==0.0.0
      - fsspec==2025.9.0
      - functional-notations==0.5.2
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.43.0
      - google-auth-httplib2==0.2.1
      - google-cloud-core==2.5.0
      - google-cloud-storage==3.5.0
      - google-crc32c==1.7.1
      - google-pasta==0.2.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - grpcio==1.74.0
      - gym==0.10.8
      - gym-notices==0.1.0
      - gymnasium==1.1.1
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.26.5
      - humanize==4.13.0
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - immutabledict==4.2.1
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jax==0.4.30
      - jax-cuda12-pjrt==0.4.30
      - jax-cuda12-plugin==0.4.30
      - jaxlib==0.4.30
      - jaynes==0.9.12
      - jinja2==3.1.6
      - jmespath==1.0.1
      - keras==3.10.0
      - kiwisolver==1.4.7
      - labmaze==1.0.6
      - lazy-loader==0.4
      - libclang==18.1.1
      - lockfile==0.12.2
      - lxml==6.0.2
      - mamujoco==1.1.0
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mc-bin-client==1.0.1
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - ml-dtypes==0.5.3
      - ml-logger==0.10.36
      - mock==5.2.0
      - more-itertools==10.8.0
      - moviepy==2.2.1
      - mpmath==1.3.0
      - mpyq==0.2.5
      - msgpack==1.1.1
      - mujoco==3.3.7
      - mujoco-py==2.0.2.5
      - multidict==4.7.6
      - namex==0.1.0
      - narwhals==2.12.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - optax==0.2.4
      - optree==0.18.0
      - orbax-checkpoint==0.6.4
      - orderly-set==5.5.0
      - packaging==25.0
      - pandas==2.3.2
      - params-proto==2.13.2
      - pettingzoo==1.23.1
      - pillow==11.3.0
      - platformdirs==4.4.0
      - plotly==6.5.0
      - portpicker==1.6.0
      - proglog==0.1.12
      - proto-plus==1.26.1
      - protobuf==3.20.3
      - psutil==7.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybullet==3.2.7
      - pycparser==2.23
      - pycurl==7.45.7
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pygame==2.6.1
      - pyglet==2.1.8
      - pygments==2.19.2
      - pymunk==7.1.0
      - pyopengl==3.1.10
      - pyparsing==3.2.4
      - pysc2==4.0.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - rdkit==2025.9.1
      - regex==2025.11.3
      - requests==2.32.5
      - requests-futures==1.0.2
      - requests-toolbelt==1.0.0
      - rfc3986==1.5.0
      - rich==14.1.0
      - rsa==4.9.1
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.14
      - s2clientprotocol==5.0.14.93333.0
      - s2protocol==5.0.14.93333.0
      - s3transfer==0.14.0
      - safetensors==0.6.2
      - sanic==20.9.0
      - sanic-cors==0.10.0.post3
      - sanic-plugins-framework==0.9.5
      - sanic-routing==22.3.0
      - scikit-image==0.24.0
      - scikit-video==1.1.11
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentry-sdk==2.38.0
      - shellingham==1.5.4
      - six==1.17.0
      - sk-video==1.1.10
      - smac==1.0.0
      - smacv2==1.0.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - supersuit==3.8.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - tap==0.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorflow-probability==0.25.0
      - tensorstore==0.1.69
      - termcolor==3.1.0
      - tifffile==2024.8.30
      - tinyscaler==1.2.8
      - toolz==1.0.0
      - torch==2.8.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - triton==3.4.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - ujson==5.11.0
      - uritemplate==4.2.0
      - urllib3==1.26.20
      - uvloop==0.22.1
      - wandb==0.21.4
      - waterbear==2.6.8
      - wcmatch==10.1
      - websocket-client==1.8.0
      - websockets==8.1
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - xyzservices==2025.11.0
      - zipp==3.23.0
prefix: /users/miniconda3/envs/mamujoco
